/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Username = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StoryId = IDL.Nat;
export const Post = IDL.Record({
  'id' : PostId,
  'createdAt' : IDL.Int,
  'author' : Username,
  'caption' : IDL.Text,
  'commentsCount' : IDL.Nat,
  'image' : ExternalBlob,
  'likesCount' : IDL.Nat,
});
export const Story = IDL.Record({
  'id' : StoryId,
  'createdAt' : IDL.Int,
  'author' : Username,
  'image' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'principal' : IDL.Principal,
  'username' : Username,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : Username,
  'postId' : PostId,
});
export const MessageId = IDL.Nat;
export const DirectMessage = IDL.Record({
  'id' : MessageId,
  'to' : Username,
  'from' : Username,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'isRead' : IDL.Bool,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'notificationType' : IDL.Text,
  'createdAt' : IDL.Int,
  'referenceId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'toUser' : Username,
  'fromUser' : Username,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUserExists' : IDL.Func([Username], [IDL.Bool], ['query']),
  'createPost' : IDL.Func([ExternalBlob, IDL.Text], [PostId], []),
  'createStory' : IDL.Func([ExternalBlob], [StoryId], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'followUser' : IDL.Func([Username], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForPost' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getConversation' : IDL.Func([Username], [IDL.Vec(DirectMessage)], ['query']),
  'getFeedForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getFollowing' : IDL.Func([], [IDL.Vec(Username)], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(DirectMessage)], ['query']),
  'getMyFollowers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getNotificationsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPostById' : IDL.Func([PostId], [Post], ['query']),
  'getPostsByUser' : IDL.Func([Username], [IDL.Vec(Post)], ['query']),
  'getStoriesByUser' : IDL.Func([Username], [IDL.Vec(Story)], ['query']),
  'getStoriesForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getUserByUsername' : IDL.Func([Username], [UserProfile], ['query']),
  'getUserFeed' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowingUser' : IDL.Func([Username], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'markMessageAsRead' : IDL.Func([MessageId], [], []),
  'markNotificationAsRead' : IDL.Func([NotificationId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([Username, IDL.Text], [MessageId], []),
  'unfollowUser' : IDL.Func([Username], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Username = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StoryId = IDL.Nat;
  const Post = IDL.Record({
    'id' : PostId,
    'createdAt' : IDL.Int,
    'author' : Username,
    'caption' : IDL.Text,
    'commentsCount' : IDL.Nat,
    'image' : ExternalBlob,
    'likesCount' : IDL.Nat,
  });
  const Story = IDL.Record({
    'id' : StoryId,
    'createdAt' : IDL.Int,
    'author' : Username,
    'image' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'principal' : IDL.Principal,
    'username' : Username,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : Username,
    'postId' : PostId,
  });
  const MessageId = IDL.Nat;
  const DirectMessage = IDL.Record({
    'id' : MessageId,
    'to' : Username,
    'from' : Username,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'isRead' : IDL.Bool,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'notificationType' : IDL.Text,
    'createdAt' : IDL.Int,
    'referenceId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'toUser' : Username,
    'fromUser' : Username,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUserExists' : IDL.Func([Username], [IDL.Bool], ['query']),
    'createPost' : IDL.Func([ExternalBlob, IDL.Text], [PostId], []),
    'createStory' : IDL.Func([ExternalBlob], [StoryId], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'followUser' : IDL.Func([Username], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForPost' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getConversation' : IDL.Func(
        [Username],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getFeedForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getFollowing' : IDL.Func([], [IDL.Vec(Username)], ['query']),
    'getInbox' : IDL.Func([], [IDL.Vec(DirectMessage)], ['query']),
    'getMyFollowers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getNotificationsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPostById' : IDL.Func([PostId], [Post], ['query']),
    'getPostsByUser' : IDL.Func([Username], [IDL.Vec(Post)], ['query']),
    'getStoriesByUser' : IDL.Func([Username], [IDL.Vec(Story)], ['query']),
    'getStoriesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getUserByUsername' : IDL.Func([Username], [UserProfile], ['query']),
    'getUserFeed' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowingUser' : IDL.Func([Username], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'markMessageAsRead' : IDL.Func([MessageId], [], []),
    'markNotificationAsRead' : IDL.Func([NotificationId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([Username, IDL.Text], [MessageId], []),
    'unfollowUser' : IDL.Func([Username], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };