/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'createdAt' : bigint,
  'text' : string,
  'author' : Username,
  'postId' : PostId,
}
export type CommentId = bigint;
export interface DirectMessage {
  'id' : MessageId,
  'to' : Username,
  'from' : Username,
  'createdAt' : bigint,
  'text' : string,
  'isRead' : boolean,
}
export type ExternalBlob = Uint8Array;
export type MessageId = bigint;
export interface Notification {
  'id' : NotificationId,
  'notificationType' : string,
  'createdAt' : bigint,
  'referenceId' : bigint,
  'isRead' : boolean,
  'toUser' : Username,
  'fromUser' : Username,
}
export type NotificationId = bigint;
export interface Post {
  'id' : PostId,
  'createdAt' : bigint,
  'author' : Username,
  'caption' : string,
  'commentsCount' : bigint,
  'image' : ExternalBlob,
  'likesCount' : bigint,
}
export type PostId = bigint;
export interface Story {
  'id' : StoryId,
  'createdAt' : bigint,
  'author' : Username,
  'image' : ExternalBlob,
}
export type StoryId = bigint;
export interface UserProfile {
  'bio' : string,
  'postCount' : bigint,
  'principal' : Principal,
  'username' : Username,
  'followerCount' : bigint,
  'followingCount' : bigint,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkUserExists' : ActorMethod<[Username], boolean>,
  'createPost' : ActorMethod<[ExternalBlob, string], PostId>,
  'createStory' : ActorMethod<[ExternalBlob], StoryId>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'followUser' : ActorMethod<[Username], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllStories' : ActorMethod<[], Array<Story>>,
  'getAllUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForPost' : ActorMethod<[PostId], Array<Comment>>,
  'getConversation' : ActorMethod<[Username], Array<DirectMessage>>,
  'getFeedForUser' : ActorMethod<[Principal], Array<Post>>,
  'getFollowing' : ActorMethod<[], Array<Username>>,
  'getInbox' : ActorMethod<[], Array<DirectMessage>>,
  'getMyFollowers' : ActorMethod<[], Array<Principal>>,
  'getNotificationsForUser' : ActorMethod<[Principal], Array<Notification>>,
  'getPostById' : ActorMethod<[PostId], Post>,
  'getPostsByUser' : ActorMethod<[Username], Array<Post>>,
  'getStoriesByUser' : ActorMethod<[Username], Array<Story>>,
  'getStoriesForUser' : ActorMethod<[Principal], Array<Story>>,
  'getUserByUsername' : ActorMethod<[Username], UserProfile>,
  'getUserFeed' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowingUser' : ActorMethod<[Username], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'markMessageAsRead' : ActorMethod<[MessageId], undefined>,
  'markNotificationAsRead' : ActorMethod<[NotificationId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Username, string], MessageId>,
  'unfollowUser' : ActorMethod<[Username], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];